spring:
  application:
    name: knowledge-service
  datasource:
    url: jdbc:h2:mem:knowledge-service;MODE=MySQL;DATABASE_TO_LOWER=TRUE;CASE_INSENSITIVE_IDENTIFIERS=TRUE;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  flyway:
    enabled: true
    default-schema: knowledge_service
    schemas:
      - knowledge_service
      - question_service
      - exam_service
      - job_service
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
server:
  port: 8082
management:
  endpoints:
    web:
      exposure:
        include: health,info
