spring:
  application:
    name: knowledge-service
  datasource:
    url: ${STUDYROMM_KNOWLEDGE_DB_URL:jdbc:mariadb://localhost:3306/knowledge_service?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai}
    driver-class-name: org.mariadb.jdbc.Driver
    username: ${STUDYROMM_KNOWLEDGE_DB_USERNAME:root}
    password: ${STUDYROMM_KNOWLEDGE_DB_PASSWORD:123456}
  flyway:
    enabled: true
    default-schema: knowledge_service
    schemas:
      - knowledge_service
      - question_service
      - exam_service
      - job_service
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
server:
  port: 8082
management:
  endpoints:
    web:
      exposure:
        include: health,info
